### ISSUE TITLE
Users can report their own posts

### ISSUE THREAD

**Issue by leomil72** [arduino/forum-issues#132]
The old forum alerted users that were trying to report their own posts.
The actual one doesn't notify nothing and let users do the report. 
Can this be fixed by adding a warning message or by bloking the notification?

**Comment by per1234** [comment]
I don't see any harm in self-reports. The moderators are going to check each flag and they are smart enough to understand when the user made an accidental flag.

Of course, accidental flags are a waste of the moderator's time, but they are (or rather were with the SMF-based forum) vastly more common on other people's posts than on the user's own post, so having some special treatment of a self flag wouldn't even help with that much.

I think the new Discourse-based forum will reduce the number of accidental flags because the flag dialog more clearly communicates what is happening.

We have already had two false flags so far, but these are caused by the interactive beginner tutorial where the bot instructs the new user to flag the bot's post as "inappropriate" in order to prove they understand how to flag posts. If the user does it right, then all is well, but it turns out that if the user does it wrong then it is treated as a legitimate flag and the moderators get a notification.
