### ISSUE TITLE
Forum search expires the cache for no good reason

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#140]
I'm trying to search for a spammer that joined today:

![screenshot from 2014-11-13 17 39 30](https://cloud.githubusercontent.com/assets/185088/5024296/46b34914-6b5c-11e4-89a7-2e26e347ce4c.png)

I click on the first match. Not him. So I hit "back arrow" to get the list again. But no:

![screenshot from 2014-11-13 17 40 05](https://cloud.githubusercontent.com/assets/185088/5024298/5d8e0962-6b5c-11e4-8da7-f0afbfe60d0d.png)

Why? What is so sensitive about a list of forum users, that I can't just go back one page in my browser, and check another one?

This is just adding effort to an already difficult job.

**Comment by matteosuppo** [comment]
It's a security measure that browser use: when there is a form, clicking on the back button doesn't execute the form again, in order to prevent unfortunate events like double bookings or double credit card charges.

I recommend opening links in other tab of the browser in order to avoid this kind of incidents.

**Comment by nickgammon** [comment]
Not always. It's not consistent. Go into your forum profile (the one where your time zone is). Hit "Change Profile". That sends the form. Now use the back button. I get the previous form back without any such error message.

However I don't seem to be able to reproduce the report right now. :)
