### ISSUE TITLE
all statistics and profile settings are gone

### ISSUE THREAD

**Issue by devpap** [arduino/forum-issues#155]
Right after the update of the arduino forums all my statistics went missing. My profile was resettet, too. No posts were made and no topics were created by my account. But I'm pretty sure I created some topics. Right now I can't look up my older post or topics in the statistics section of my profile. Example:
Link to post: http://forum.arduino.cc/index.php?topic=271200.0 At this post I'm marked as guest.
![no_topics](https://cloud.githubusercontent.com/assets/3677413/5423273/64df8b36-82b4-11e4-8d2d-6b99d146d916.PNG)
Is it possible to restore the missing information and link it to my profile again?

**Comment by per1234** [comment]
Hi @devpap. I'm very sorry to hear this happened to you and that you didn't receive any response. Unfortunately, I think it has been so long since it happened that there will be no way to investigate this. So I'll go ahead and close this as unresolveable.

If anyone has similar issues, feel free to open another issue.
