### ISSUE TITLE
Limit the ability to post to old threads

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#161]
Example: http://forum.arduino.cc/index.php?topic=226683.msg2034860#msg2034860

A fairly meaningless post was added to this thread, after a delay of 10 months. Such posts are quite often the precursor to spam, as the poster tries to "look legitimate". The post was:

> since he did not get back on this simple, yet crucial little problem, i will say this solves delay() issues for arduino and tiny indeed!
> thanks olf2012

(You can't really say that the above post added any useful information to the discussion. This was the first post for this forum user. This could have been written by almost anyone by extracting out a few keywords from earlier posts, like "delay", "arduino", and "tiny" - two of which were in the thread title).

I suggest that threads be automatically blocked from new posts if they are old (eg. more than 3 months) as this is usually someone just hijacking an old thread when starting a new one would be more appropriate. 

Alternatively, limit the ability to add to old threads to people with (say) 100+ posts to their names, who are therefore established forum members.

**Comment by raschemmel** [comment]
I don't think any software can know if the post added to an old post is legit or not. A Global Moderator
is qualified to decide that. I think the forum objective is to provide reference database for forum members and therefore if a new post on an old thread accomplishes that objective I would say it should
be allowed.

**Comment by nickgammon** [comment]
I don't agree with this. I just found another old thread (started in 2013) where someone had added a (completely irrelevant) extra question. It is easy to miss that the thread was started years ago, and assume that the original poster is still interested in your replies.

If a case can be made that the old thread contains egregiously wrong material, then a moderator (who would have to power to edit it) could modify the old thread, eg. by adding a link to a newer thread which corrects the information, or add a correction.

However, for people who have just joined the forum, and done a Google search, and found something vaguely relating to their problem (eg. "serial communications") to hijack and old thread, is just silly.

Let's make the default that you **can't** add to old threads, but you can always make a new one, and point out to the moderators that thread X from 5 years ago is now incorrect (if anyone cares).

**Comment by raschemmel** [comment]
"However, for people who have just joined the forum, and done a Google search, and found something vaguely relating to their problem (eg. "serial communications") to hijack and old thread, is just silly."

I agree, and I never suggested otherwise. This is why I said no software could tell if something added is relevant enough to be allowed to be added and since we cannot expect the Global Moderators to be
able to find the time to remove added comments that are not relevant to the thread then that only leaves one remaining option and that is to NOT allow new comments to an old thread. I think Nick and I are on the same page but got our signals crossed. I think he was basically just saying it is not
physically (or practically ) possible for Global Moderators to find and eliminate irrelevant new comments to an old thread (or hijackers) and thus new comments should not be allowed, period
I agree with that because there is no other option.

**Comment by per1234** [comment]
Hi nickgammon. Thanks for taking the time to make this suggestion Topics are now locked after four months without activity.
