### ISSUE TITLE
Karma is STILL broken

### ISSUE THREAD

**Issue by smeezekitty** [arduino/forum-issues#172]
Seems like this has gone on a little long.
There is STILL two [Add Karma] links and STILL not Karma display.

Why is this still broken?

**Comment by TomGeorge1956** [comment]
I don't even know what my karma is, my profile is wrong.
Ditto....Why is this still broken?

**Comment by mastrolinux** [comment]
The first one should be the number of karma point, the second link should remain as "add Karma"

**Comment by TomGeorge1956** [comment]
I don't think anything has been done.
I now get posts from spanish language forum, that I haven't even read.
I'm sure some of the posts I answer to, never get listed back to me when another post is added.

Still majority of first posters don't use code tags because its use is not predominant when they compose their thread.
The icons are Too small, they need to be 5 times bigger with their functions WRITTEN in them.

Tom

**Comment by mastrolinux** [comment]
Karma display is fixed. Closing this one
