### ISSUE TITLE
If attachment cannot be uploaded, message is posted anyway

### ISSUE THREAD

**Issue by nickgammon** [arduino/forum-issues#182]
If you make a post with an attachment which is a disallowed type (eg. .hex file) the post goes ahead anyway, without the attachment:

> There was a problem during the uploading of Blink.cpp.hex.
>    You cannot upload that type of file. The only allowed extensions are doc, gif, jpg, mpg, pdf, png, txt, zip, c, h, cpp, ino, pde.

This is kind-of confusing, because your post might say "I attach Blink.cpp.hex" but you don't attach it! If the attachments cannot be uploaded, perhaps the post should not be made.

**Comment by matteosuppo** [comment]
The software policy is to post the message, warn the user about the missing attachment and give the option to go back and edit the message.

![an error has occurred](https://cloud.githubusercontent.com/assets/1532793/6684234/844254ca-cc8f-11e4-8620-59b2d1937902.png)

This prevents the user from having to reuploading all of their attachments if only one failed.

I would prefer changing the text and making the Back button more visible instead of changing the way the forum behaves.

**Comment by nickgammon** [comment]
Perhaps add wording like:

> Your **post has been made**, however the above attachment was not attached. Please use the Back button to edit your post and submit any required changes.
