### ISSUE TITLE
7-Zip

### ISSUE THREAD

**Issue by Coding-Badly** [arduino/forum-issues#185]
> There was a problem during the uploading of LiquidCrystal_I2C plus TinyWireM.7z.
> You cannot upload that type of file. The only allowed extensions are doc, gif, jpg, mpg, pdf, png, txt, zip, c, h, cpp, ino, pde.

Please add support for 7-Zip files.  Everything about the format is superior to ZIP files.

**Comment by per1234** [comment]
Hi @Coding-Badly. Are you still in favor of this proposal?

The reason I ask is because, as time has passed, it seems like there has not been a strong adoption of the 7z format. I would argue that only allowing .zip files is beneficial in the context of the Arduino forum because if we allow people to use less common compression types when sharing things on the forum, this will result in that content being less accessible to many forum members.

**Comment by Coding-Badly** [comment]
> Are you still in favor of this proposal?

Of course.

> ...there has not been a strong adoption of the 7z format...

The adoption has been zero.  The forum doesn't allow the format.

> ...content being less accessible...

For those living with slow internet speeds, which is the vast majority of the world, the smaller content will be more accessible.

**Comment by per1234** [comment]
>The adoption has been zero. The forum doesn't allow the format.

I meant adoption by the entire world. Not adoption specifically on the Arduino Forum.

>the smaller content will be more accessible.

How common is it for people to share archives via forum attachments that are large enough for the difference in size between the two formats to be meaningful? I don't recall many instances of it.

**Comment by Coding-Badly** [comment]
> I meant adoption by the entire world.

A fallacy.  Lovely.

I'm not going to waste my time knocking down straw men.
