### ISSUE TITLE
please enlarge maximum  number of characters in a post 

### ISSUE THREAD

**Issue by shiftleftplusone** [arduino/forum-issues#192]
could you please enlarge the maximum  number of characters in a post ?
Currently it's limited to 9000 which is extremely poor IMO (already my customized BareMinimum already exceeds this limit actually).
16000 would be fair,
32000 would be very fine!

To my experience posted code can be checked lot easier if you see it in a code block rather than if you had to download attached files,
additionally it's easier to correct errors in posted code rather than in an uploaded code.
So more space for viewable code size in code boxes would be a tremendous benefit to everybody!

And please note that raising the limit would not cause either user then to spam the forums with code automatically.

**Comment by nickgammon** [comment]
Related thread, if you want discussion about this: http://forum.arduino.cc/index.php?topic=347407.0

**Comment by RobTillaart** [comment]
the forum limits reflect perfectly the limited resources of the Arduino's ;)
And limited resources trigger people to start thinking

practical answer: large files you can attach as zip

**Comment by VogonJeltz** [comment]
resources of the Arduinos !=  limited resources of AVRs
and what it actually reflects is anything but perfect for long files, but even for short ones it's not satisfactorily.

"o my experience posted code can be checked lot easier if you see it in a code block rather than if you had to download attached files,
additionally it's easier to correct errors in posted code rather than in an uploaded code.
So more space for viewable code size in code boxes would be a tremendous benefit to everybody!"

**Comment by per1234** [comment]
The limit has now been raised to 32000, just as requested!
