### ISSUE TITLE
Post URL in forum discussion

### ISSUE THREAD

**Issue by ffissore** [arduino/forum-issues#197]
_From @budvar10 on October 27, 2015 6:37_

Unable to post the URL in correct form. Autocorrect engine or what alway modyfied so the link is mismatched and it doesn't work.

_Copied from original issue: arduino/Arduino#4031_

**Comment by gepd** [comment]
I've noted the same problem. I reportered here: http://forum.arduino.cc/index.php?topic=355917.0

**Comment by budvar10** [comment]
Thanks, I'm using FF and this problem persists pretty long time beside 
of others. We will see...
:)

**Comment by per1234** [comment]
Hi @budvar10. Thanks so much for reporting this bug! Since the forum system has been completely changed by the switch to Discourse this week, I'm going to guess this issue is now fixed. If I'm wrong about that, please comment here and I'll reopen the issue. I'll definitely be keeping an eye out for any reoccurrences of this annoying bug and will be sure to reopen if I spot it again.
