### ISSUE TITLE
Notifications: Receive Email // Receive Alert

### ISSUE THREAD

**Issue by 00alis** [arduino/forum-issues#205]
If I select 'Receive Email' or 'Receive Alert' from the Notification options and then I press Refresh the page, the label is changed to 'Receive Email and Alert'

**Comment by 00alis** [comment]
@samura

**Comment by samura** [comment]
Please test this. I didn't check if the notifications are sent. Only that the value stored on the DB is the value displayed.

**Comment by 00alis** [comment]
we need to test this together, if we both subscribe to a test board and add messages we can see if we receive emails/alerts
let's try with this one http://forumdev.arduino.cc/index.php?board=95.0

is the change live on forumdev?
If i select 'Receive email' option and hit refresh I get 'Receive Emails and Alerts' again

**Comment by samura** [comment]
Inverted the option to receive e-mail with the reply/post by default on the email body.

Need to run this query on the production server so that everyone that opted-in for "receive message body in e-mails" will still receive them.

`DELETE FROM smf_user_alerts_prefs WHERE alert_pref="msg_receive_body"`

**Comment by Chris--A** [comment]
@00alis 
@samura 

Since activation of these features on the production site, a lot of people are complaining:

[Who is messing around with my notification settings ?](https://forum.arduino.cc/index.php?topic=400460.0)
[How to stop email alerts](https://forum.arduino.cc/index.php?topic=399982.0)
[Can't Disable E-Mail Notifications When I Reply To a Thread!](https://forum.arduino.cc/index.php?topic=400567.0)

Until its fixed, can you at least disable the emails. People get alerts now when they're on the forum. No need to fill their inbox while they are away.

**Comment by 00alis** [comment]
Ok let me understand this right, if you select the 'Do Not Receive Email' option on a board/topic you don't want to receive any email, even if you write on a thread, is this the suggested behavior?

![screenshot 2016-05-16 16 54 36](https://cloud.githubusercontent.com/assets/6151328/15293238/6180e9cc-1b87-11e6-832f-43740b1b7922.png)

@mastrolinux

**Comment by Chris--A** [comment]
Yes, this is correct. People are using this dialog as well as this settings page: http://forum.arduino.cc/index.php?action=profile;area=notification;sa=alerts

They are still receiving emails.

I personally do not have this problem, as I disabled mine a long time ago before the SMF version upgrade. However others are de-selecting the options to receive emails and saving, however the settings revert and visiting the settings page still shows the options selected.

I think until this can be fixed, it might be better to prevent any emails from being sent regardless of the setting. Everyone will still receive alerts when they visit the site.

**Comment by 00alis** [comment]
Ok sounds good, I leave it to @mastrolinux and management to schedule the fix. Thank you so much for your report1

**Comment by per1234** [comment]
Since the notifications system has been completely changed by the switch to Discourse, this issue is now obsolete.
