### ISSUE TITLE
Allow everybody to modify their own posts even before 5 min

### ISSUE THREAD

**Issue by 00alis** [arduino/forum-issues#208]
Right now if I post something and I notice a typo I have to wait 5 minutes before I am able to edit it

**Comment by Bodmer** [comment]
Yep, that one is a right pain. Please fix.

**Comment by agdl** [comment]
+1 and please remove this on different topics

**Comment by 00alis** [comment]
@mastrolinux this is really slowing down the effort of giving support on the forum , any improvement will be really appreciated <3

**Comment by akash73** [comment]
me too on the queue

**Comment by Chris--A** [comment]
Yup, this needs to be fixed. It is becoming a regular issue with new posters.

**Comment by KilianB** [comment]
Some more attention in 2018

**Comment by teo1978** [comment]
Is the source code of the forum also available somewhere?

**Comment by Serjlee** [comment]
Hello all,

this annoying issue was about the spam prevention measure which limits the amount of posts new users can publish to once every 5 minutes until 100 posts.

That measure interfered with edits because it wasn't able to distinguish between new posts and edits when checking the timer.  We weren't too sure whether or no this was just annoying or also useful against spammer, so we finally decided to test a temporary solution.

Since a few days ago:
- Users with less than 100 posts can only post once every 5 minutes, like before
- Users with less than 100 posts can edit any post after _30 seconds_ passed since the latest post (down from 5 minutes)

We are going to test this solution for a bit, and then decide if it's a good idea to lower the cooldown for edits  even more (or remove it altogether)

Please open a new issue if that fix doesn't work as publicized!
