### ISSUE TITLE
Notification Issues

### ISSUE THREAD

**Issue by samura** [arduino/forum-issues#213]
- [x] Changing auto_notify option on notification settings does not get saved
- [x] Always display the "Notify me" checkbox on quick-reply and reply
- [x] ~~If a person sets the "Disable alerts", "Notify me" option should be disabled~~ **Since we now see the checkbox, will not change the default option https://www.dropbox.com/s/rxb0pcsaswxvnmg/Screenshot%202016-06-11%2014.55.57.png?dl=0**
- [ ] If a person deletes the account, it continues to receive notifications **how can we test this?**
- [x] Disabling "Notify me of:" "Nothing at all" does not stop the emails  **I can see this as being a complain source: when a member checks the "Nothing at all" and forgets about it, and later check one "Receive e-mail" but the e-mails never arrive. We should find a way of remembering the member that "Receive e-mails" won't work while the "Nothing at all" option is activated?**
- [ ] E-mail links are using http instead of https **Can't reproduce: https://www.dropbox.com/s/no2eme3ommpv6zt/Screenshot%202016-06-11%2012.39.27.png?dl=0**
- [x] Using "Notify me of replies." sets the topic as watched but still says "No Alerts or E-mails"

**Comment by samura** [comment]
@mastrolinux can you please review the ones with bold text?

**Comment by mastrolinux** [comment]
3. makes sense
4. You can create an arbitrary username and you can delete it from id.arduino.cc, right now we do not have a real api to check for it. I do know we have something but not sure if reliable, will give you access
5. what we can do is alert the user if he checks "receive e-mails" and it has "nothing at all" active, maybe a warning is fine
6. maybe you are trying on forumdev but I can assure you 100% of my emails have http instead of https: please do not use the $scheme but put there statically https://

Thanls

**Comment by samura** [comment]
https://www.dropbox.com/s/gmv4f2q1nt6sv1z/Screenshot%202016-06-19%2020.51.56.png?dl=0

**Comment by samura** [comment]
![screenshot 2016-06-19 20 51 56](https://cloud.githubusercontent.com/assets/1213250/16179504/c68bd2bc-365f-11e6-83f3-cf5350dd779e.png)

**Comment by samura** [comment]
#4: Can you check $SystemSettingsForum or $DeploySettingsURL if it's not using http? I'm using the variable $scripturl that is being used all over the site: if this is wrong, a lot of things are.

**Comment by per1234** [comment]
Closing as obsoleted by this weeks switch to a Discourse-based forum.

If anyone is still finding any of these issues or features to be relevant, please open a new issue.
