### ISSUE TITLE
Feature Request to move link.

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/forum-issues#222]
Is there any chance the link at the bottom of the page [https://forum.arduino.cc/](url)
Can be moved to the top of the page alongside the " Alerts Unread Posts Updated Topics" link ?

Seems to make more sense to have it at the top rather than the bottom.
That link also seems to have a limit of 10 pages when there are more posts than that.

**Comment by per1234** [comment]
Hi @BallscrewBob. Thanks for taking the time to request this feature.

Since the forum system has been completely changed by the switch to Discourse, I'm going to guess this issue is now obsolete. If I'm wrong about that, please comment here with a more detailed description and I'll reopen the issue.
