### ISSUE TITLE
 Updating Arduino AVR Boards

### ISSUE THREAD

**Issue by maddy2610** [arduino/forum-issues#225]
I am using IDE 1.6.9....... And after updating Arduino AVR Boards to v. 1.6.12, I can no longer uplload to board.
Going back to v. 1.6.11 and it works again.

Tried this on Arduino Mega2560 and Nano. Same result.

Any idea?

i have just bought Arduino products from this site www.w11stop.com/ard-uino in pakistan...

**Comment by per1234** [comment]
Also posted at http://forum.arduino.cc/index.php?topic=468968.0
- This is completely the wrong place to submit problems related to the Arduino IDE or Arduino AVR Boards.
- You should always test using the latest versions before submitting a bug report. There is no point for submitting reports of bugs that were fixed 8 months ago.
- We're already trying to help you on the forum. If you would have taken the time to respond instead of cross-posting we would already have your problem solved.
