### ISSUE TITLE
Users banned as "Sock puppet" for no reason

### ISSUE THREAD

**Issue by per1234** [arduino/forum-issues#233]
As previously reported at https://github.com/arduino/forum-issues/issues/177#issuecomment-298292857 @Andy2No and I have both been permanently banned from the forum and both of us believe this was an error rather than a result of our actions. My user name on the Arduino forum is pert. There was one other report of this happening after the website update on 2017-04-27 near the start of this forum thread:
http://forum.arduino.cc/index.php?topic=473506
I'm unable to link to the exact reply in that thread because I can't even browse the forum now (https://github.com/arduino/forum-issues/issues/177)!

I get this same message when I try to visit the forum:
![de0c4fba-2e3f-11e7-9019-e1302913444a](https://cloud.githubusercontent.com/assets/8572152/25574118/1c1e3420-2e00-11e7-9c63-94b953104b75.gif)

**Comment by Andy2No** [comment]
Hi Pert!

It was you I was trying to thank - for the advice about using Github too, 
which has been a bit of a mystery to me, for some time.

I was just about to press the submit button on another post on the Github 
issue, so I'll do that next, but it seems the solution (maybe temporarily) 
is to clear your browser history.  It might just be cookies, if not try site 
preferences etc.  I did and it let me back in, without needing to log in.

I'm feeling a bit shell shocked :)  I hope it works for you too.

Best Regards,

Andy

----- Original Message ----- 
From: per1234
To: arduino/forum-issues
Cc: Andy2No ; Mention
Sent: Monday, May 01, 2017 7:55 AM
Subject: [arduino/forum-issues] Users banned as "Sock puppet" for no reason 
(#233)


As previously reported at #177 (comment) @Andy2No and I have both been 
permanently banned from the forum and both of us believe this was an error 
rather than a result of our actions. My user name on the Arduino forum is 
pert. There was one other report of this happening after the website update 
on 2017-04-27 near the start of this forum thread:
http://forum.arduino.cc/index.php?topic=473506
I'm unable to link to the exact reply in that thread because I can't even 
browse the forum now (#177)!
I get this same message when I try to visit the forum:

**Comment by per1234** [comment]
Hey, that's cool that I helped you and now you are helping me. Thanks!

I cleared the browser cache and still couldn't get in. Then I cleared my cookies and that solved the problem. So it may be that you only need to clear cookies. I'll leave this issue open for a while since I'm sure others are having the same problem and they will be more likely to see this issue if it's open.

**Comment by Andy2No** [comment]
Cool.  I'm glad to hear it.  I just hope it stops at having to do that, and doesn't mean it stops working all together in one browser, as mentioned in the link I posted in the other thread:

http://forum.arduino.cc/index.php?topic=211822.0

Sorry.  Still tired, and slightly shell shocked.  I hope this isn't to disjointed.

**Comment by per1234** [comment]
It just happened to me again, and I was able to solve it again by deleting cookies.

**Comment by Lennyz1988** [comment]
I deleted my cookies in Firefox but I am still unable to use the forum while logged in. Without logging in it works.

**Comment by per1234** [comment]
I haven't heard any new reports of this issue so I'm going to assume it's fixed.
