### ISSUE TITLE
lost screen name on forum software update

### ISSUE THREAD

**Issue by ghost** [arduino/forum-issues#234]
Since the forum software changed a few days ago all my posts display my real life name instead of my screen name.   I don't see anywhere in the profile to enter a screen name. 

I would delete the account but fear that all my posts will be out there forever and I will be unable to delete them.  

How can I restore my screen name to my hundreds of posts already on the forum?

**Comment by nickgammon** [comment]
I also cannot find any way of changing my user name back to what it was. It isn't a major deal for me (my name is now "nickgammon" rather than "Nick Gammon") however it looks stupid. Can someone please be assigned to fix this?

**Comment by per1234** [comment]
Hi @nickgammon. I don't know whether you have visited the forum in the last few days. It has been switched from using the SMF forum software to [Discourse](https://github.com/discourse/discourse). I see that your "username" and "name" are both set to "nickgammon", while your "title" is set to "Nick Gammon":
https://forum.arduino.cc/u/nickgammon/summary
This results in your posts being headed as "nickgammon Nick Gammon". Example:
https://forum.arduino.cc/t/typing-the-keypad-enter-with-the-keyboard-library/237353/11

Discourse does not allow suppressing your user name in any way, so this "nickgammon" will always be shown. You can set your "name" to anything you like, but that is only shown when people look at your profile or profile preview. You can also change or remove your "title" if you like.

So I'm going to have to close this as not possible to resolve. Sorry about that.

**Comment by nickgammon** [comment]
My posts were always shown as from "Nick Gammon" (prior to 2017) and you say this is impossible to fix? Surely the "display name" (that people see) can be modified? I mean, I only want things to go back to how they were for years. I am hardly "suppressing" my identity, it is clear we are the same person.

**Comment by per1234** [comment]
We are using a completely different forum software now. There are inevitably going to be differences.

One of the reasons it was necessary to make this change to the forum is because Arduino had made modifications to the SMF forum software code. That resulted in an unacceptable situation where they were stuck with a version of SMF that was years out of date with no possibility of updating it. So there will be no tinkering around with the forum code this time around.

Discourse does have a lot of configuration options and plugins. So if you can find one that allows your desired functionality, you are welcome to submit a proposal to Arduino to make that change.

In my opinion, the current situation is perfectly fine. I don't see any problem with you being shown as "nickgammon".
