### ISSUE TITLE
502 errors

### ISSUE THREAD

**Issue by BallscrewBob** [arduino/forum-issues#243]
`
504 Gateway Time-out

awselb/2.0
`

8.00 AM EST

This follows Yesterdays issues  but the additional info seems to be "awselb/2.0"

**Comment by BallscrewBob** [comment]
Marking as closed as they seem to have dissipated...Second time in 2 days

**Comment by Serjlee** [comment]
Just to clarify: this exact issue happens when redirected to hydra.arduino.cc and the SSO is down, so it's not actually a forum issue (you can check this by trying to log in on the store or the homepage).

We are currently investigating on those (diminishing) random SSO outages, but currently they should be fixed by themselves in ~1-2 minutes.

Still, thank you for noticing us!
