### ISSUE TITLE
PM: where do I see the messages I send?

### ISSUE THREAD

**Issue by 00alis** [arduino/forum-issues#245]
I am having a hard time finding my own messages in the section of the Arduino Forum, I can see all the answers but not the beginning of the thread. I find this quite confusing...

**Comment by BallscrewBob** [comment]
The "PM's" are not "thread orientated" if you are talking about "PM's"
I dont like the format for those as I have to switch between "sent" and "received" which is quite clunky  and would much rather see them in a thread format continuous stream **(feature request)**
So yes that part is or can be confusing and probably more so to newcomers.

Which particular section Alice ? as I know the CREATE section tends to miss "NEW" posts notification icon quite a lot and I always have to check it manually without knowing if there are new ones or not.

**Comment by per1234** [comment]
To see the messages you sent you have to hover over the **Messages** tab, then select **Sent Items**:
![clipboard01](https://cloud.githubusercontent.com/assets/8572152/26647547/92c145d4-45f4-11e7-9057-ecf037583ab4.png)
I had trouble finding it initially and then I use it so infrequently that I've had to rediscover it a couple times since because I had forgotten where it was.

@BallscrewBob I just found a useful feature:
1. Hover over **Preferences** tab
2. Click **Change Settings**
3. Select **As a conversation** from the **Display personal messages:** menu.
4. Click **Change Settings**

**Comment by 00alis** [comment]
Thank you so much @per1234, it is for sure in a very wired place!
