### ISSUE TITLE
5 Minutes

### ISSUE THREAD

**Issue by Coding-Badly** [arduino/forum-issues#258]
Currently, users with less than 100 posts have to wait 5 minutes between posts and edits.  Please change the policy to only include creating new topics.  The change solves a few problems without compromising the reason for the limit.

**Comment by delta-G** [comment]
I concur!

**Comment by Constant-Confusion** [comment]
I wrote a simple algorithm that detects this more efficiently than just a single variable while utilizing the existing variables at your disposal. I do not think you want this information revealed to the public though. Since you are a mod at the forum you should have access to my email. I do not have much experience with text based language so I would need your help transferring from my native programming language. It should be just a few lines of code and I have tested this.

**Comment by Coding-Badly** [comment]
I do not have access to the backside of the forum.
If the Arduino folks are interested I suspect they will contact you.

**Comment by teo1978** [comment]
The limit is meant to apply only to new posts. The fact that it prevents you from saving edits to an existing post is clearly just a bug (a very annoying one).

The error message is even the same (it says you cannot publish a new post, when actually what you are trying to do is save edits to an existing post). Also, it will allow you to do several edits within 5 minutes, but it won't allow you to save edits to a post if you have posted something in the last 5 minutes, whether it's the post you're trying to edit or not.

**Comment by Serjlee** [comment]
See https://github.com/arduino/forum-issues/issues/208#issuecomment-376096400
