### ISSUE TITLE
Please make posts uneditable after 1 day

### ISSUE THREAD

**Issue by RobTillaart** [arduino/forum-issues#264]
This is also a recurring problem. People that want their problem removed from the forum after getting a (partial) solution. Do they want to hide their homework or? 

imho it is against the spirit of an open source forum.

This is today's example - http://forum.arduino.cc/index.php?topic=503608.msg3434830#msg3434830

**Comment by per1234** [comment]
This could also prevent spammers from making seemingly legitimate posts or replies and then later editing the spam in after they've made it past the initial scrutiny. I have seen the former quite a bit but not the latter that I can recall. Maybe that just means it works.

The downside I can see to this is, for example, if I have something like a support thread for a project where I want to edit the download link in the first post of the thread on every release. Now I could just add a new reply to the thread for each release but on an active thread that can require the reader to do a lot of digging rather than getting all the info they need right at the top of the thread.

**Comment by RobTillaart** [comment]
Or "a restore original text" option?  undo edit?

THe downside is indeed a good point...

**Comment by BallscrewBob** [comment]
Just bumping this but for a slightly different reason.
There was a slew of vandalised posts by the OP's which rendered all the assistance unintelligible in terms of reference. 
Only way was to delete what had been in some cases quite valuable information had the original been there. 
From the standpoint of a moderator I would love to see Robs option to RESTORE original text.

**Comment by RobTillaart** [comment]
@cmaglie 
Imho this looks still relevant on the forum but if no action is taken, this issue can better be closed.

**Comment by BallscrewBob** [comment]
It is still a very relevant feature request (present or future)...Two posts vandalised last week that I deleted and not sure about other mods.
