### ISSUE TITLE
Banned from forum

### ISSUE THREAD

**Issue by Patto21** [arduino/forum-issues#319]
Hi 
I have been banned from the forum yesterday.
I tried to post a screenshot and got banned??
Can anyone help please
the message i got was

Sorry patto21, you are banned from using this forum!
spam
This ban is not set to expire.

I cleared all history, tried on both Firefox and Chrome and no luck

TIA

**Comment by per1234** [comment]
Hi @Patto21. pert from the Arduino Forum here. I took a look at the ban and it was made by the forum's automated spam detection system. I don't have any idea what triggered it. Sorry about that.

I have removed the ban on your forum account. Please check if your account is now reinstated. If not, please let me know and I'll fix it. Otherwise, you can go ahead and close this issue as resolved.

Regards, Per

**Comment by Patto21** [comment]
Thanks Pert
I'll post that question about 404 again
Thanks again for your help
